# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  train:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        make install
    - name: Create envfile
      env:
        ENV_FILE: ${{ secrets.ENV_FILE }}
      run: |
        echo $ENV_FILE | base64 --decode > .env
    - name: Train model
      run: |
        make train
    - uses: actions/upload-artifact@v4
      with:
        name: model
        path: ml/model/model.pkl
        retention-days: 30
        compression-level: 0
        overwrite: true
    - uses: actions/upload-artifact@v4
      with:
        name: pred_data
        path: data/results
        retention-days: 30
        compression-level: 0
        overwrite: true